LABELS:
  - 早会
  
ISSUE_BODY: |
  > 此 issue 由机器人自动发送

  时间：09:00

  固定 zoom 会议室：
  https://zoom.us/j/9552592803

  例行环节：开发协调

  本次早会预定沟通内容：
  请在下方回复补充
  
COMMENTS:
  - |
    会议时长：30 分钟

    会议纪要：
    - 待补充
  - |
    早会参会者可自由回复此 issue
