ISSUE_BODY: |
  > 此 issue 由机器人自动发送

  时间：21:00

  固定 zoom 会议室：
  https://zoom.us/j/9552592803

  例行环节一：专项工作协调沟通
  例行环节二：提案讨论

LABELS:
  - 周会
  
# 议程安排
AGENDA: |
  ### 议程安排

  环节一：专项工作协调沟通

  专项|推动者
  -|-
  <%= projectsMarkdown %>

  ------

  环节二：提案讨论（未讨论则顺延）

  提案汇总链接：
  https://github.com/sibbay-ai/cooperation-issues/wiki/proposals-list

  提案|链接
  -|-
  ..|.. 
