ISSUE_BODY: |
  > 此 issue 由机器人自动发送

  时间：21:00

  固定 zoom 会议室：
  https://zoom.us/j/9552592803

  例行环节一：专项工作协调沟通
  例行环节二：提案讨论

LABELS:
  - 周会
  
# 议程安排
AGENDA: |
  ### 议程安排

  #### 环节一：专项工作协调沟通

  专项|推动者
  -|-
  <%= projectsMarkdown %>

  ------

  #### 环节二：提案讨论（未讨论则顺延）

  提案汇总链接：
  https://github.com/sibbay-ai/cooperation-issues/wiki/proposals-list

  提案|链接
  -|-
  ..|.. 

# 会议纪要
SUMMARY: |
  ### 会议纪要

  会议耗时：1 小时

  #### 环节一（40 分钟）
  
  ------

  #### 环节二（20 分钟）

  提案|链接|已讨论|表决结果
  -|-|-|-
  ..|..|..|..

  将由 committer 委员会对上述执行结论进行表决
  
COMMENTS:
  - |
    周会参会者可自由回复此 issue
  - |
    > 此楼用于记录周会出勤

# 专项
PROJECTS:
  - name: 后端优化
    mc: sinchb
  - name: 运维与后台
    mc: fushang318
  - name: 小程序 1.11.0
    mc: zhaobinglong
  - name: 小程序设计迭代
    mc: nancy919
  - name: 数据分析统计
    mc: bqx619
  - name: token 与奖励模型
    mc: ben7th
  - name: MRI 增强开发
    mc: ben7th
  - name: 开发者社区推动
    mc: ben7th
  - name: 健康专家与用户社区推动
    mc: fazhen
